typography_spectrum: 0.3499000440351665
color:
  brandStrength: 0.7469532594550401
  lightness: 0.57307228888385
  saturation: 0.4607506259344518
  rhythmicContrast: 0.28428543801419437
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
layout_spectrum: 0.2279738497454673
name: Volunteering Tropical Agriculture/Agroforestry
title: Ina-nay nga Pag-uswag sa Boluntarismo
description: Slow Progression of Volunteerism
